SET SERVEROUTPUT ON
	ACCEPT NUM NUMBER PROMPT 'Enter a number: '
DECLARE
	NUM NUMBER:= &NUM;
	TEMP NUMBER:= NUM;
	ADD NUMBER:=0;
	DIGIT NUMBER;
BEGIN
	WHILE TEMP != 0
	LOOP
		DIGIT:= TEMP MOD 10;
		ADD:= ADD + DIGIT*DIGIT*DIGIT;
		TEMP:= FLOOR(TEMP/10);
	END LOOP;
	
	IF ADD = NUM THEN
		DBMS_OUTPUT.PUT_LINE(NUM || ' is an armstrong number');
	ELSE
		DBMS_OUTPUT.PUT_LINE(NUM || ' is not an armstrong number');
	END IF;
END;
/