SET SERVEROUTPUT ON

ACCEPT N NUMBER PROMPT 'ENTER A VALUE'

DECLARE
	N NUMBER:=&N;
BEGIN
	IF N MOD 2 = 0 THEN
		DBMS_OUTPUT.PUT_LINE(N || ' is even');
	ELSE
		DBMS_OUTPUT.PUT_LINE(N || ' is odd');
	END IF;
END;
/